# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestInit():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_init(self):
    self.driver.get("http://127.0.0.1/")
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    elements = self.driver.find_elements(By.XPATH, "//*[@id=\"table-proj_table\"][contains(.,\'Project Deployment Test 1\')]")
    assert len(elements) == 0
    elements = self.driver.find_elements(By.XPATH, "//*[@id=\"table-proj_table\"][contains(.,\'Project Deployment Test 2\')]")
    assert len(elements) == 0
    self.driver.find_element(By.LINK_TEXT, "New Project").click()
    self.driver.find_element(By.ID, "app_title").send_keys("Project Deployment Test 1")
    dropdown = self.driver.find_element(By.ID, "purpose")
    dropdown.find_element(By.XPATH, "//option[. = 'Practice / Just for fun']").click()
    self.driver.find_element(By.ID, "project_template_radio1").click()
    self.driver.find_element(By.CSS_SELECTOR, "input[name=\"copyof\"][value=\"3\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primaryrc").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"ExternalModules/manager/project.php\"]").click()
    self.driver.find_element(By.ID, "external-modules-enable-modules-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"project_deployment\"] .enable-button")))
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"project_deployment\"] .enable-button").click()
    time.sleep(5)
    elements = self.driver.find_elements(By.CSS_SELECTOR, "#external-modules-enabled tr[data-module=\"project_deployment\"]")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"ProjectSetup/index.php\"]").click()
    self.driver.execute_script("$(\'#south\').remove()")
    self.driver.find_element(By.ID, "setupEnableSurveysBtn").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "south")))
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"online_designer.php\"]").click()
    self.driver.execute_script("$(\'#south\').remove()")
    self.driver.find_element(By.CSS_SELECTOR, "button[onclick*=\"create_survey\"][onclick*=\"patient_morale_questionnaire\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "south")))
    self.driver.execute_script("$(\'#south\').remove()")
    self.driver.find_element(By.ID, "surveySettingsSubmit").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "south")))
    self.driver.execute_script("sessionStorage.setItem(\'sourceproject\',window.location.search.replace(/[?&]pid=([0-9]+)/,\'$1\'))")
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"ProjectSetup/index.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"ProjectSetup/other_functionality.php\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "button.btn-rcgreen[onclick*=\"copy_project_form.php\"]").click()
    self.driver.find_element(By.ID, "app_title").send_keys("Project Deployment Test 2")
    self.driver.find_element(By.CSS_SELECTOR, "a[onclick*=\"$(\'#copy_checkboxes input[type=checkbox]:not(:disabled)\').prop(\'checked\',true)\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "button.btn-rcgreen[onclick*=\"document.createdb.submit\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//div[@id=\'subheader\'][contains(.,\'Project Deployment Test 2\')]")))
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"ExternalModules/manager/project.php\"]").click()
    self.driver.find_element(By.ID, "external-modules-enable-modules-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"project_deployment\"] .enable-button")))
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"project_deployment\"] .enable-button").click()
    time.sleep(5)
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "tr[data-module=\"project_deployment\"] .external-modules-configure-button")))
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"project_deployment\"] .external-modules-configure-button").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "input[name=\"source-project\"]")))
    self.driver.execute_script("$(\'input[name=\"source-server\"]\').val(window.location.origin)")
    self.driver.execute_script("$(\'input[name=\"source-project\"]\').val(sessionStorage.getItem(\'sourceproject\'))")
    self.driver.find_element(By.CSS_SELECTOR, "#external-modules-configure-modal button.save").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"ExternalModules/\"][href*=\"prefix=project_deployment\"]").click()
    self.driver.execute_script("$(\'#south\').remove();if(window.location.hostname==\'127.0.0.1\'){$(\'input[name=\"username\"]\').val(\'admin\');$(\'input[name=\"password\"]\').val(\'abc123\');$(\'form[method=\"post\"] input[type=\"submit\"]\').trigger(\'click\')}else{setTimeout(function(){$(\'form[method=\"post\"]\').css(\'background\',\'#fee\')},2000);setTimeout(function(){$(\'form[method=\"post\"]\').css(\'background\',\'\')},3000);setTimeout(function(){$(\'form[method=\"post\"]\').css(\'background\',\'#fee\')},4000);setTimeout(function(){$(\'form[method=\"post\"]\').css(\'background\',\'\')},5000)}")
    WebDriverWait(self.driver, 90).until(expected_conditions.presence_of_element_located((By.ID, "south")))
    self.vars["count"] = self.driver.execute_script("return \'\' + $(\'.changestbl tr\').length")
    assert(self.vars["count"] == 1)
  
