# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestT05Userrolesupdate():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_t05Userrolesupdate(self):
    self.driver.get("https://redcap03.nottingham.ac.uk//")
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    elements = self.driver.find_elements(By.XPATH, "//*[@id=\"table-proj_table\"][contains(.,\'Project Deployment Test 1\')]")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.XPATH, "//*[@id=\"table-proj_table\"][contains(.,\'Project Deployment Test 2\')]")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "Project Deployment Test 1").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"UserRights/index.php\"]").click()
    self.driver.find_element(By.ID, "new_rolename").click()
    self.driver.find_element(By.ID, "new_rolename").send_keys("Role1")
    self.driver.find_element(By.ID, "createRoleBtn").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".ui-dialog button[style*=\"bold\"]")))
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog button[style*=\"bold\"]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH, "//*[@id=\'user_rights_roles_table\']//td[contains(.,\'Role1\')]")))
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    self.driver.find_element(By.LINK_TEXT, "Project Deployment Test 2").click()
    self.driver.find_element(By.CSS_SELECTOR, "a[href*=\"ExternalModules/\"][href*=\"prefix=project_deployment\"]").click()
    self.driver.execute_script("if(window.location.hostname==\'127.0.0.1\'&&$(\'input[name=\"username\"]\').length>0){$(\'input[name=\"username\"]\').val(\'admin\');$(\'input[name=\"password\"]\').val(\'abc123\');$(\'form[method=\"post\"] input[type=\"submit\"]\').trigger(\'click\')}")
    WebDriverWait(self.driver, 30).until(expected_conditions.invisibility_of_element_located((By.CSS_SELECTOR, "input[name=\"username\"]")))
    self.vars["count"] = self.driver.execute_script("return \'\' + $(\'.changestbl tr\').length")
    assert(self.vars["count"] == 2)
    elements = self.driver.find_elements(By.CSS_SELECTOR, "input[name=\"update[roles]\"]")
    assert len(elements) > 0
    element = self.driver.find_element(By.CSS_SELECTOR, "input[name=\"update[roles]\"]")
    if element.is_selected() != True: element.click()
    self.driver.find_element(By.CSS_SELECTOR, "input[type=\"submit\"]").click()
    self.vars["count"] = self.driver.execute_script("return \'\' + $(\'.changestbl tr\').length")
    assert(self.vars["count"] == 1)
  
